Updating tag logic

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -181,8 +181,17 @@ jobs:
             sed -i "s/setup_version=\".*\"/setup_version=\"$version\"/" etc/module.xml
             git add composer.json etc/module.xml
             git commit -m "v$version"
+            git tag $version -am "v$version"
             git push -u origin ctdoriott/test
           name: Bump Version In Files
+      - run:
+          command: |
+            if ! git push -u origin ctdoriott/test --follow-tags; then
+              echo "Push failed. Please add this CircleCI deploy key to your repo with write access:"
+              ssh-keygen -y -f ~/.ssh/id_rsa
+              exit 1
+            fi
+          name: Tag Release in GitHub
       - run:
           command: |
             echo {} > package.json
